### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by garrett-he** [pypi/support#5034] opened 2024-10-30 14:02 UTC
### PyPI Username

garrett-he

### Reason for request

Lost access to email address

### Recovery Codes

- [x] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [x] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment] 2024-11-01 23:12
Duplicate of #4578

**Closed by Thespi-Brain** 2024-11-01 23:12 UTC
Labels: account-recovery
