### ISSUE TITLE
files.pythonhosted.org serves invalid certificate

### ISSUE THREAD

**Issue by arnaudsjs** [pypi/support#3462] opened 2023-12-14 09:57 UTC
**Describe the bug**

Executing pip sometimes fails with the following warning/error:

```
08:56:41    python3.11 -m venv /opt/venv
08:56:41 + /opt/venv/bin/pip3 install -U pip wheel setuptools
08:56:41 Requirement already satisfied: pip in /opt/venv/lib64/python3.11/site-packages (22.3.1)
08:56:41 Collecting pip
08:56:41   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:41   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'"))': /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl
08:56:42   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:42   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'"))': /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl
08:56:42   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:43   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'"))': /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl
08:56:43   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:45   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'"))': /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl
08:56:45   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:49   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'"))': /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl
08:56:49   WARNING: Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'm.sni-311-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', 'Certainly'),), (('commonName', 'Certainly Intermediate R1'),)), 'version': 3, 'serialNumber': 'DB3FF7E06E8CBBFC07727137DF9FB698A0B4', 'notBefore': 'Nov 28 05:32:06 2023 GMT', 'notAfter': 'Dec 28 05:32:05 2023 GMT', 'subjectAltName': (('DNS', 'm.sni-311-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.int-r1.certainly.com/',), 'caIssuers': ('http://int-r1.certainly.com/',)}
08:56:49 ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl (Caused by SSLError(CertificateError("hostname 'files.pythonhosted.org' doesn't match 'm.sni-311-default.ssl.fastly.net'")))
08:56:49
```

It doesn't consistently fails, sometimes the certificate validation also just works.

**Expected behavior**

The certificate validation succeeds consistently.

**To Reproduce**

See output snippet above.

**My Platform**

* OS: Rocky Linux 8
* Version openssl package: openssl==1:1.1.1k-9.el8_7

**Comment by miketheman** [comment] 2023-12-19 14:52
@arnaudsjs Please look at the reporting details in this template.
https://github.com/pypi/support/issues/new?assignees=&labels=network&projects=&template=access-issues.yml

These may help figuring out what's going on here - since it's not apparent from the current report how to reproduce the issue.

**Comment by woodruffw** [comment] 2023-12-19 15:14
I'm unable to reproduce this with the `openssl s_client` oneliner, unfortunately -- I consistently get a `*.pythonhosted.org` subject. That being said, I'm probably on a different Fastly PoP than you are.

**Comment by ewdurbin** [comment] 2023-12-19 15:54
`m.sni-311-default.ssl.fastly.net` is suspect to me.

we migrated DNS over three weeks ago to our own map: https://github.com/pypi/infra/commit/3ec868764e066f89dca27fe512f0a063c3f7d419

this is likely stale DNS somewhere.

**Comment by miketheman** [comment] 2023-12-19 19:40
@arnaudsjs We've continued to investigate, and the current conclusion is that somewhere along the path one of your DNS resolvers is returning a stale DNS record.

Since we have the DNS CNAME record TTL set to 86400 seconds (1 day) and the change was made ~3 weeks ago, the record should have propagated to all DNS servers that respect the TTL. If a resolver is misbehaving, that could explain it.

If you can determine which resolver is returning the incorrect record (possibly via `dig files.pythonhosted.org`) that shows the response for the erroring call, that might help you determine which resolver is not playing nicely.

**Comment by arnaudsjs** [comment] 2023-12-20 08:16
You are right. The issue is indeed related to DNS. This is the dig output I get when the wrong certificate is returned:

```
$ dig files.pythonhosted.org
; <<>> DiG 9.11.36-RedHat-9.11.36-11.el8_9 <<>> files.pythonhosted.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24680
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;files.pythonhosted.org.		IN	A

;; ANSWER SECTION:
files.pythonhosted.org.	0	IN	CNAME	dualstack.m.sni.global.fastly.net.
dualstack.m.sni.global.fastly.net. 0 IN	A	146.75.73.55

;; AUTHORITY SECTION:
fastly.net.		171238	IN	NS	ns1.fastly.net.
fastly.net.		171238	IN	NS	ns2.fastly.net.
fastly.net.		171238	IN	NS	ns3.fastly.net.
fastly.net.		171238	IN	NS	ns4.fastly.net.

;; ADDITIONAL SECTION:
ns1.fastly.net.		171233	IN	A	23.235.32.32
ns2.fastly.net.		171233	IN	A	104.156.80.32
ns3.fastly.net.		171233	IN	A	23.235.36.32
ns4.fastly.net.		171233	IN	A	104.156.84.32

;; Query time: 0 msec
;; SERVER: 192.168.26.1#53(192.168.26.1)
;; WHEN: Wed Dec 20 08:57:25 CET 2023
;; MSG SIZE  rcvd: 299
```

This `146.75.73.55` host indeed returns the wrong certificate:

```
$ openssl s_client -connect 146.75.73.55:443 -servername files.pythonhosted.org 2>&1 </dev/null |grep -i 'subject'
subject=CN = m.sni-311-default.ssl.fastly.net
```

**Comment by miketheman** [comment] 2023-12-20 15:34
@arnaudsjs Thanks for providing the dig output.

This does indeed confirm that something in your DNS resolver path is returning a cached entry. That's not something we control - from dig we can see that the DNS server your machine is using is `192.168.26.1` (not a public IP) so something in that DNS instance or it's configured resolvers may not be expiring the entry correctly.

I'll close this issue, since there's nothing from our side that we can fix.

**Closed by miketheman** 2023-12-20 15:34 UTC
Labels: network, status: awaiting response

**Comment by bartv** [comment] 2023-12-20 15:37
This is not correct. Our local cache has been cleared. (On monday the entire lab was rebooted)

**Comment by miketheman** [comment] 2023-12-20 15:42
@bartv Thanks for sharing the @ server address! I get the correct result:

```shellsession
$ dig @96.45.45.45 files.pythonhosted.org

; <<>> DiG 9.10.6 <<>> @96.45.45.45 files.pythonhosted.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12383
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;files.pythonhosted.org.		IN	A

;; ANSWER SECTION:
files.pythonhosted.org.	83531	IN	CNAME	dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net. 20 IN	A	146.75.28.223

;; AUTHORITY SECTION:
fastly.net.		164687	IN	NS	ns1.fastly.net.
fastly.net.		164687	IN	NS	ns2.fastly.net.
fastly.net.		164687	IN	NS	ns3.fastly.net.
fastly.net.		164687	IN	NS	ns4.fastly.net.

;; ADDITIONAL SECTION:
ns1.fastly.net.		164687	IN	A	23.235.32.32
ns2.fastly.net.		164687	IN	A	104.156.80.32
ns3.fastly.net.		164687	IN	A	23.235.36.32
ns4.fastly.net.		164687	IN	A	104.156.84.32

;; Query time: 89 msec
;; SERVER: 96.45.45.45#53(96.45.45.45)
;; WHEN: Wed Dec 20 10:41:39 EST 2023
;; MSG SIZE  rcvd: 295
```

**Comment by bartv** [comment] 2023-12-20 15:43
As you can see in my screenshot when I do the request 2 times with 1 second interval I get both results.

This dns service is from fortinet, which provides us with TLS DNS services.

**Comment by miketheman** [comment] 2023-12-20 15:49
@bartv yes, I can see that. (It's more helpful to post terminal output as text vs screenshots, since I can't copy&paste anything from a screneshot)

I ran this for a bit, and didn't want to overwhelm the DNS server, and consistently get the correct response.

```shellsession
$ while true; do dig +short CNAME @96.45.45.45 files.pythonhosted.org ; sleep 1 ; done
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
dualstack.python.map.fastly.net.
^C%
```

I'd recommend you contact the Fortinet DNS service and surface the issue to them. As noted previously, our change was some 3 weeks ago, and we have a 1-day TTL on the CNAME record (you can confirm this with `dig +trace files.pythonhosted.org` which will walk the entire resolver tree.
