### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by stryngs** [pypi/support#2416] opened 2022-11-21 00:21 UTC
### PyPI Username

stryngs

### Reason for request

I lost access to the stryngs account on pypi.  I believe it is tied to a domain which I no longer own.  I've logged into all my emails and the associated addresses have not received the "recover password" email; thus I am stuck.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2022-11-21 15:39
Confirmed that these emails are bouncing. Please email support@pypi.org including a link to this issue from the email address you would like to have associated with the account.

**Comment by ewdurbin** [comment] 2023-06-03 13:50
Hi, You should look into configuring SPF/DKIM for your domain so that Google accepts the email. Unfortunately this is the address you need to contact: support@pypi.org

**Comment by Thespi-Brain** [comment] 2024-09-18 22:15
Hi @stryngs,

I am following up regarding your request. Are you still having an issue regarding your email address and logging in? Let me know, and I will start an account recovery process for you to update your email and reset your account, thanks!

**Comment by Thespi-Brain** [comment] 2024-10-21 22:07
Closing due to non response

**Closed by Thespi-Brain** 2024-10-21 22:07 UTC
Labels: account-recovery
