### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by thekaveman** [pypi/support#3071] opened 2023-08-02 16:29 UTC
### PyPI Username

`cal-itp-bot`

### Reason for request

I enabled 2FA with an authentication app, but somehow the config did not save in my app. Now 2FA is enabled on the PyPI account but I cannot generate a TOTP code. 

I do still have the recovery codes so I can still login to my account. However, I am not able to remove the existing 2FA config, nor am I able to add a new authentication app (because PyPI thinks I already have one!)

🙏 Thank you

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-08-04 14:57
This is a duplicate of https://github.com/pypi/warehouse/issues/14274

Please follow that issue for resolution.

**Closed by ewdurbin** 2023-08-04 14:57 UTC
Labels: account-recovery
