### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by fobos123deimos** [pypi/support#4901] opened 2024-10-10 19:20 UTC
### PyPI Username

pikachu123deimos

### Reason for request

I am unable to access the authentication application and I am unable to use my recovery code

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment] 2024-10-10 20:10
Duplicate of https://github.com/pypi/support/issues/4900, closing.

**Closed by Thespi-Brain** 2024-10-10 20:10 UTC
Labels: account-recovery
