### ISSUE TITLE
PEP 541 Request: pystack

### ISSUE THREAD

**Issue by tonyseek** [pypi/support#2500] opened 2023-01-04 12:06 UTC
### Project to be claimed

`pystack`: https://pypi.org/project/pystack

### Your PyPI username

`tonyseek`: https://pypi.org/user/tonyseek

### Reasons for the request

I am the maintainer of https://github.com/wooparadog/pystack and I found that `pystack` has been used in PyPI. For now, I publish the pystack to https://pypi.org/project/pystack-debugger as a workaround. But some people may be mislead to install it with incorrect name `pip install pystack` instead of the correct and longer name `pip install pystack-debugger`.

The https://pypi.org/project/pystack doesn't have any document, license, and project home page. But it has an uploaded package without any description. It seems like an abandoned project but still installable. I am not sure whether it is safe to install it or not.

I am requesting to take the PyPI project name `pystack` to keep people from installing unexpected and unsafe artifacts. Please review this request. Thank you.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/wooparadog/pystack

### Contact and additional research

I cannot contact the current maintainer since there is not any document and any email address in the project page.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by larryhastings** [comment] 2023-02-09 17:05
FWIW, I got curious and took a look.  The current "pystack" project is a stub project with literally zero useful code.  (The only "source code" is `setup.py` which doesn't do any real work.)  So it seems like it's just a name squatting package, which is against PyPI terms of service:

https://docs.npmjs.com/policies/disputes/#squatting

It seems that the user who published "pystack", mariocj89, has published multiple name-squatting packages, including "bloomberg", "hostinfo", "sqlalchemy-comdb2", and "libnlp".  I admit I didn't actually examine these packages, but each of these .tar.gz files is < 1k, so... how much work could they be doing?

https://pypi.org/user/mariocj89/

(Note, I'm not a PyPI representative, just an interested bystander.)

**Comment by yeraydiazdiaz** [comment] 2023-04-02 16:57
Hi @tonyseek, I can confirm what @larryhastings stated. The owners seem to be https://github.com/pablogsal and https://github.com/Mariocj89 who are active in GitHub, hopefully they can transfer the project to you.

**Comment by yeraydiazdiaz** [comment] 2023-04-02 16:58
Let's try actually mentioning them this time @mariocj89 @pablogsal

**Comment by mariocj89** [comment] 2023-04-03 06:25
Hello @yeraydiazdiaz , we have been in the process of open sourcing a project named `pystack` which is why you currently see a placeholder for the name. We are days away from announcing it as we are finishing up the work on making this work everywhere.

This is a project we've been working on for years and expect to make available for everyone in the coming weeks. The project source-code is available already under https://github.com/bloomberg/pystack

> So it seems like it's just a name squatting package 

It's not, we reserved the name as this has been a multi-year effort project that we have been piloting within Bloomberg and we want to opensource.

> It seems that the user who published "pystack", mariocj89, has published multiple name-squatting packages

It's actually to prevent name-squatting. I was creating these before it was possible to request PyPI to block a name (also, it is easier to just "reserve the name" than to request PyPI to block it).

Thanks for reaching out @yeraydiazdiaz

**Comment by yeraydiazdiaz** [comment] 2023-04-03 07:32
Hi @mariocj89, thanks for your quick reply. So reserving a name by uploading a blank project is not allowed, but it's quite  common which is why we attempt contact with the owners before simply transferring the projects.

In this case I will not be transferring the project.

@mariocj89 you mention there are more like this, so it would be good to at least upload pre-release package describing your intentions towards the project name, a link to the GitHub repository would be great as well so people can see it's an active project that is just not ready for release.

**Closed by yeraydiazdiaz** 2023-04-03 07:32 UTC
Labels: PEP 541

**Comment by mariocj89** [comment] 2023-04-03 08:03
Thank you @yeraydiazdiaz, I've sent an email to pypi admin to request those packages to be blocked rather than "reserving the name" and I've [uploaded a pre-release](https://pypi.org/project/pystack/2.11.1rc0/) to show the real intent of the project.

For context, I reserved the package name to try and minimize the work needed on pypi side, as otherwise it takes 2 emails/2 actions on pypi side:

1. Blocking the name when we start to opensource the package.
2. Unblocking it when we finish.

**Comment by pradyunsg** [comment] 2023-04-03 10:04
> The page I linked to above was linked to in a PyPI policy discussion, but it's not itself a PyPI policy document.

For posterity, the PyPI policy is documented at https://peps.python.org/pep-0541/.

**Comment by larryhastings** [comment] 2023-04-03 10:54
Ah, so name-squatting *is* [explicitly disallowed:](https://peps.python.org/pep-0541/#invalid-projects)

> **Invalid Projects**
>
> A project published on the Package Index meeting ANY of the following is considered invalid and will be removed from the Index: [...]
> * project is name squatting (package has no functionality or is empty);

So mariocj89 and pablogsal lucked out, as you chose not to enforce the letter of the law.

mariocj89, your name-squatting didn't save the PyPI admins any time, because they don't "block" and "unblock" names on request.  They're overworked as it is, and they don't have the time to add managing this imaginary name reservation system you've dreamed up.  There is simply no mechanism for reserving of names--it's always first-come, first-serve.  The first registrant who uploads a legitimate package under an unused name gets it.

**Comment by di** [comment] 2023-04-03 17:13
> mariocj89, your name-squatting didn't save the PyPI admins any time, because they don't "block" and "unblock" names on request. They're overworked as it is, and they don't have the time to add managing this imaginary name reservation system you've dreamed up. There is simply no mechanism for reserving of names--it's always first-come, first-serve. The first registrant who uploads a legitimate package under an unused name gets it.

We do block/unblock names on request, usually when a user/organization/project has demonstrated that they have a legitimate use for a project name, aren't ready to publish, but don't want to violate our namesquatting policy.

Generally we realize that the combination of our "first come first served" and "no namesquatting" policies make it hard to identify/coordinate a project name if you're planning a big release of your open source project on PyPI.

(We also block names on request which might be used by an attacker for dependency-confusion attacks, but we usually ask that these are namespaced in some way with a prefix, and when they aren't we often release these names to other users when they can demonstrate they intend to use them legitimately.)

Given that:

> we have been in the process of open sourcing a project named pystack which is why you currently see a placeholder for the name. We are days away from announcing it as we are finishing up the work on making this work everywhere.

I will verify with @mariocj89 that this is indeed the case, and if so, the outcome here will stand. (And I ask that @mariocj89 reach out to `admin@pypi.org` in advance next time instead of namesquatting).

**Comment by mariocj89** [comment] 2023-04-03 17:28
> We do block/unblock names on request, usually when a user/organization/project has demonstrated that they have a legitimate use for a project name, aren't ready to publish, but don't want to violate our namesquatting policy.

That is indeed what I referred to.

> Generally we realize that the combination of our "first come first served" and "no namesquatting" policies make it hard to identify/coordinate a project name if you're planning a big release of your open source project on PyPI.

That is exactly what we are doing with pystack.

> I will verify with @mariocj89 that this is indeed the case, and if so, the outcome here will stand. (And I ask that @mariocj89 reach out to admin@pypi.org in advance next time instead of name-squatting).

Sure, check out the codebase at https://github.com/bloomberg/pystack. The commit history is removed to preserve Bloomberg IP, as it used to contain references to proprietary tools. This is a tool that we (Mainly Pablo at that day TBH) started to develop 3 years ago and that we've always intended to make opensource. 
3 years ago we did not "reserve" the name, and someone created a project on pypi.org with the same name. I reached out to the owner via email and he agreed to pass the name to us, see https://github.com/pypi/support/issues/2187

>  (And I ask that @mariocj89 reach out to admin@pypi.org in advance next time instead of namesquatting).

Sure thing, just did that for the pending ones and will do it for all future ones. Please note many of the packages I created were created back in 2020, not sure if there was even a process to block things at that time.
