### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by aminul71bd** [pypi/support#2614] opened 2023-02-17 19:33 UTC
### PyPI Username

aminul

### Reason for request

I didn't have 2F authentication app when I selected 2F authentication

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-02-28 14:30
Duplicate of #2612

**Closed by ewdurbin** 2023-02-28 14:30 UTC
Labels: account-recovery
