### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by HenraL** [pypi/support#3165] opened 2023-09-09 10:12 UTC
### PyPI Username

`Hanra`

### Reason for request

Dear Pypi Support Team,

I would like to appologies for the redundency of creating a new issue, however, my problem has not been solved.

I had already opened an issue two days ago #3155 to ask if you could help connect to my account because I have ***lost*** **the authenticator app as well as my recovery codes** (more details on why in the previous issue).

The answer you provided to my problem was: 
```
User **Hanra** has valid recovery codes generated as of 2022-08-15 19:21:22.562221.

Please use those recovery codes to regain access to your account.
```

But if I do not have the file, how am I supposed to use the recovery codes.

Could you please help me regain access to my account, (i.e. send me a new set of 2FA codes or the old ones again) or if possible you could disable 2FA for me.

I do hope that you can help me.

I understand security is vital, and I apologize for any inconvenience.
I kindly request your assistance in resolving this issue and providing guidance on recovering my account.

Thank you very much for your help.
Hanra

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-09-15 14:27
Closed as duplicate of #3155, we will continue tracking your issue there.

**Closed by ewdurbin** 2023-09-15 14:27 UTC
Labels: account-recovery
