### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Inventrohyder** [pypi/support#2618] opened 2023-02-19 10:26 UTC
### PyPI Username

inventrohyder

### Reason for request

Lost 2FA authentication app

This is for both pypi and test.pypi
It was the same app that I used for both

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [x] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-02-19 13:03
Please complete the acknowledgement for this issue to be processed.

**Comment by Inventrohyder** [comment] 2023-02-19 23:16
Thanks @ewdurbin

**Comment by ewdurbin** [comment] 2023-02-28 14:32
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by Inventrohyder** [comment] 2023-02-28 23:36
Acknowledgement of having followed email instructions.

**Comment by ewdurbin** [comment] 2023-03-06 12:23
closed as duplicate of #2597

**Closed by ewdurbin** 2023-03-06 12:23 UTC
Labels: account-recovery
