### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by damiengueho** [pypi/support#3588] opened 2024-01-30 21:28 UTC
### PyPI Username

damien28

### Reason for request

I got locked out of my account. I haven't generated any recovery codes. 
This is a continuing issue from: https://github.com/pypi/support/issues/3285
It's been 3+ months I've been locked out of my account without any solution for a possible recovery. I suspect my previous Account Recovery Issue has been skipped or forgotten, so creating a new one, hoping to get a resolution.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2024-02-02 14:21
Duplicate of #3285

**Closed by ewdurbin** 2024-02-02 14:21 UTC
Labels: account-recovery
