### ISSUE TITLE
Users not receiving verification or reset password emails

### ISSUE THREAD

**Issue by xaoyaoo** [pypi/support#3275] opened 2023-10-15 03:09 UTC
Describe the bug
Users not receiving verification email and reset password email. I tried to reset the password and register a new one, but I've receive no email from PyPI.

Expected behavior

Users should receive email when reseting password.
Users should receive verification email when registering a new account.
To Reproduce
From PyPI website, reset the password or register a new account.

My Platform
(irrelevant)

My Account xaoyaoo

**Comment by miketheman** [comment] 2023-10-16 15:23
Hello @xaoyaoo !

Looks like you were able to receive the verification and confirmation emails successfully. Closing.

**Closed by miketheman** 2023-10-16 15:23 UTC
Labels: support

**Comment by xaoyaoo** [comment] 2023-10-17 01:25
I was able to succeed now because I changed my email address again, but I never received the verification email when I used my Gmail address.

Of course, I can use it now. My issue has been resolved, but the bug still exists.

**Comment by miketheman** [comment] 2023-10-17 13:59
I've checked again and confirmed that we show successful delivery to both of the email addresses on your account.
Sometimes Gmail flags certain emails as spam, had you checked that folder?
Specifically from `noreply@pypi.org`

**Comment by xaoyaoo** [comment] 2023-10-17 14:04
Sorry about that, I did check before but couldn't find the email. I just double-checked and found it in my spam folder. Thank you so much for your patience in handling this issue.

**Comment by miketheman** [comment] 2023-10-17 14:41
Glad it all worked out!
