### ISSUE TITLE
PEP 541 Request: tfit

### ISSUE THREAD

**Issue by nasirxo** [pypi/support#2870] opened 2023-05-29 17:08 UTC
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/tfit

### Your PyPI username

`USER_NAME`: https://pypi.org/user/nasirxo

### Reasons for the request

i mistakenly deleted it now i am not able to use this name again

### Maintenance or replacement?

None

### Source code repositories URLs

https://github.com/nasirxo/TFIT

### Contact and additional research

i was owner of the orignal project

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment] 2024-08-23 13:08
This issue is a duplicate of #2863, so I'll close it.

Unfortunately, I can't help with the request itself at this time.

**Closed by encukou** 2024-08-23 13:08 UTC
Labels: PEP 541
