### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by KohnoseLami** [pypi/support#3117] opened 2023-08-22 14:36 UTC
### PyPI Username

KohnoseLami

### Reason for request

I lost access to 2FA because my smartphone broke down.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-09-01 13:06
Contacted via primary email address on the account, please read the instructions and reply to proceed with recovery.

**Comment by ewdurbin** [comment] 2023-09-01 13:07
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by ewdurbin** [comment] 2023-09-01 13:08
Confirmed bouncing. Please contact [support@pypi.org](mailto:support@pypi.org), reference this issue, and send from the address you'd like to have associated with the account, we will use that for verification. Please note: This address must not be associated with an existing pypi.org account.

**Comment by Thespi-Brain** [comment] 2024-09-23 21:00
Hi @KohnoseLami,

I am following up regarding your request. Are you still having an issue regarding your recovery codes and logging in? Let me know, and I will start an account recovery process for you to reset your account, thanks!

**Comment by Thespi-Brain** [comment] 2024-10-11 22:39
Closing due to non response

**Closed by Thespi-Brain** 2024-10-11 22:39 UTC
Labels: status: awaiting response, account-recovery
