### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by siddharthdis** [pypi/support#4566] opened 2024-08-16 07:40 UTC
### PyPI Username

siddharthdis

### **Reason for Request:**
I am requesting the permanent deletion of my PyPI account because I have lost access to my 2FA authentication app and the associated recovery code. This has completely locked me out of my account (username: "siddharthdis"), and I am unable to regain access.

### **Attempts to Resolve:**
Over the past year, I have made multiple attempts to contact PyPI support via email but have not received any assistance or resolution. 

### **Expected Outcome:**
Given the extended duration without resolution and the inconvenience this has caused, I am requesting the permanent deletion of my account. This will allow me to recreate it and regain access to the platform.

### **Account Details:**
- **Username:** siddharthdis
- **Registered Email:** siddharthdis3432@gmail.com

### **Additional Information:**
I would appreciate prompt assistance with this matter to avoid further delays in my work.

**Thank you,**
Siddharth Dis

### Recovery Codes

- [X] I never generated or have lost access to the recovery codes for my account

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by Thespi-Brain** [comment] 2024-08-23 18:19
Duplicate of #4018

**Closed by Thespi-Brain** 2024-08-23 18:19 UTC
Labels: account-recovery
