### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Tiezhengyuan** [pypi/support#3694] opened 2024-03-01 15:13 UTC
### PyPI Username

tiezhengyuan

### Reason for request

Hello,
I can't login. The code generated by the authenticator on my iphone is not recognized by PyPi. I have not recovery code.  I created a similar request before. the feedback is always "User tiezhengyuan has valid recovery codes generated as of 2023-12-27 14:11:28.437902".  I am really confused. Please believe me I don't know where is the recovery code. Would you please give me some hints how can I get back recovery code. I really appreciated that.  thanks.
Tiezheng

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2024-03-01 15:21
closing as duplicate of #3672

**Closed by ewdurbin** 2024-03-01 15:21 UTC
Labels: account-recovery
