### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by cracker911181** [pypi/support#2534] opened 2023-01-21 12:05 UTC
### PyPI Username

(cracker911181)

### Reason for request

Lost 2FA authentication mobile.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-01-30 12:34
Closing as duplicate of #2533

**Closed by ewdurbin** 2023-01-30 12:34 UTC
Labels: account-recovery
