### ISSUE TITLE
PEP 541 Request: fsrl

### ISSUE THREAD

**Issue by liuzuxin** [pypi/support#2816] opened 2023-05-07 15:56 UTC
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/fsrl

### Your PyPI username

`USER_NAME`: https://pypi.org/user/zuxinl

### Reasons for the request

Hi, I want to upload my package named `fsrl` on pypi, there is no existing package named `fsrl`, but I still encounter the error said: `The name 'fsrl' is too similar to an existing project`. Can you help to figure out why and address the problem? Thank you.

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/liuzuxin/fsrl

### Contact and additional research

There is no owner for the `fsrl` package.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by encukou** [comment] 2024-08-23 13:03
This issue is a duplicate of #2865, so I'll close it.

Unfortunately, I can't help with the request itself at this time.

**Closed by encukou** 2024-08-23 13:03 UTC
Labels: PEP 541
