### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by Tiezhengyuan** [pypi/support#3630] opened 2024-02-11 16:37 UTC
### PyPI Username

tiezhengyuan

### Reason for request

Hi

Authentication code isnot working. pypi login always  shows that the code is invalid. I don't know where is recovery code, too
I could be reached out by tiezhengyuan@hotmail.com

Thanks

Tiezheng

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2024-02-23 15:52
User `tiezhengyuan` has valid recovery codes generated as of 2023-12-27 14:11:28.437902.

Please use those recovery codes to regain access to your account.

**Comment by ewdurbin** [comment] 2024-03-01 15:21
closing as duplicate of #3672

**Closed by ewdurbin** 2024-03-01 15:21 UTC
Labels: account-recovery

**Comment by Tiezhengyuan** [comment] 2024-03-01 15:24
@ewdurbin  sorry about for bothering you.  I know created duplicated tickets. Please don't close this issue. I need you help me out. I don't know where is my recovery code. would you please give me some hints or suggestions ? thanks
