### ISSUE TITLE
Account recovery request

### ISSUE THREAD

**Issue by vedem1192** [pypi/support#3061] opened 2023-07-31 13:58 UTC
### PyPI Username

`vdemers`

### Reason for request

I changed phone, and therefore I am trying to port 2FA to my new phone app, however when trying to add a new TOTP authenticator, I get the following error : `Error Account cannot be linked to more than one authentication application at a time`. The "remove" option on 2FA app is also greyed.

At this point I am logging with recovery codes, but that isn't sustainable and I would need to be able to rely on my new 2FA app for that.

Thanks!

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

### Acknowledgement

- [X] I understand that it may take a significant amount of time to process my account recovery request.

**Comment by ewdurbin** [comment] 2023-08-04 14:57
This is a duplicate of https://github.com/pypi/warehouse/issues/14274

Please follow that issue for resolution.

**Closed by ewdurbin** 2023-08-04 14:57 UTC
Labels: account-recovery
